swagger: "2.0"
info:
  title: Bank Argent API documentation
  description: Contains all available API endpoints in this codebase
  version: "1.0.0"
  termsOfService: "http://swagger.io/terms/"
host: localhost:3001
basePath: /api/v1
schemes:
  - http

paths:
  /user/login:
    post:
      tags:
        - User Module
      summary: Login
      description: API for Login
      parameters:
        - in: body
          name: body
          description: Login Payload
          required: true
          schema:
            $ref: "#/definitions/Login"
      produces:
        - application/json
      responses:
        "200":
          description: Login Successfully
          schema:
            $ref: "#/definitions/LoginResponse"
        "400":
          description: Invalid Fields
        "500":
          description: Internal Server Error

  /user/signup:
    post:
      tags:
        - User Module
      summary: Signup
      description: API for Signup
      parameters:
        - in: body
          name: body
          description: Signup Payload
          required: true
          schema:
            $ref: "#/definitions/User"
      produces:
        - application/json
      responses:
        "200":
          description: Signup Successfully
          schema:
            $ref: "#/definitions/ApiResponse"
        "400":
          description: Invalid Fields
        "500":
          description: Internal Server Error

  /user/profile:
    post:
      security:
        - Bearer: []
      tags:
        - User Module
      summary: User Profile API
      description: API for fetching a user profile
      responses:
        "200":
          description: User profile retrieved successfully
          schema:
            $ref: "#/definitions/ApiResponse"
        "400":
          description: Invalid Fields
        "500":
          description: Internal Server Error
    put:
      security:
        - Bearer: []
      tags:
        - User Module
      summary: User Profile API
      description: API for updating a user profile
      parameters:
        - in: body
          name: body
          description: Update user profile attributes
          required: true
          schema:
            $ref: "#/definitions/UserProfile"
      produces:
        - application/json
      responses:
        "200":
          description: User profile updated successfully
          schema:
            $ref: "#/definitions/ApiResponse"
        "400":
          description: Invalid Fields
        "500":
          description: Internal Server Error

  /user/account:
    get:
      security:
        - Bearer: []
      tags:
        - User Module
      summary: Get User Account Information
      description: API for fetching user account details
      responses:
        "200":
          description: User account details retrieved successfully
          schema:
            $ref: "#/definitions/Account"
        "400":
          description: Invalid Request
        "500":
          description: Internal Server Error
    post:
      security:
        - Bearer: []
      tags:
        - User Module
      summary: Create User Account
      description: API for creating a user account
      parameters:
        - in: body
          name: body
          description: Account creation details
          required: true
          schema:
            $ref: "#/definitions/Account"
      responses:
        "201":
          description: User account created successfully
        "400":
          description: Invalid Fields
        "500":
          description: Internal Server Error

  /user/account/transaction:
    get:
      security:
        - Bearer: []
      tags:
        - User Module
      summary: Get Account Transactions
      description: API for fetching transactions of a user account
      responses:
        "200":
          description: List of user account transactions retrieved successfully
          schema:
            type: array
            items:
              $ref: "#/definitions/Transaction"
        "400":
          description: Invalid Request
        "500":
          description: Internal Server Error
    post:
      security:
        - Bearer: []
      tags:
        - User Module
      summary: Add a Transaction
      description: API for adding a new transaction to the user account
      parameters:
        - in: body
          name: body
          description: Transaction details
          required: true
          schema:
            $ref: "#/definitions/Transaction"
      responses:
        "201":
          description: Transaction added successfully
        "400":
          description: Invalid Fields
        "500":
          description: Internal Server Error
    put:
      security:
        - Bearer: []
      tags:
        - User Module
      summary: Edit a Transaction
      description: API for editing the type and note of an existing transaction
      parameters:
        - in: body
          name: body
          description: Transaction edit details
          required: true
          schema:
            $ref: "#/definitions/Transaction"
      responses:
        "200":
          description: Transaction updated successfully
        "400":
          description: Invalid Fields
        "500":
          description: Internal Server Error

  /user/account/transaction/current-month:
    get:
      security:
        - Bearer: []
      tags:
        - User Module
      summary: Get Transactions for the Current Month
      description: API for fetching transactions of a user account for the current month
      responses:
        "200":
          description: List of user account transactions for the current month retrieved successfully
          schema:
            type: array
            items:
              $ref: "#/definitions/Transaction"
        "400":
          description: Invalid Request
        "500":
          description: Internal Server Error

securityDefinitions:
  Bearer:
    type: apiKey
    name: Authorization
    in: header

definitions:
  User:
    properties:
      email:
        type: string
        description: user email
      password:
        type: string
        description: user password
      firstName:
        type: string
        description: user first name
      lastName:
        type: string
        description: user last name
      userName:
        type: string
        description: user public name

  Login:
    properties:
      email:
        type: string
        description: user email
      password:
        type: string
        description: user password

  ApiResponse:
    type: object
    properties:
      status:
        type: integer
      message:
        type: string
      body:
        type: object
        properties:
          id:
            type: string
          email:
            type: string

  LoginResponse:
    type: object
    properties:
      token:
        type: string

  UserProfile:
    type: object
    properties:
      userName:
        type: string

  Account:
    properties:
      id:
        type: string
        description: unique identifier for the account
      userId:
        type: string
        description: user identifier the account is attached to
      balance:
        type: number
        format: double
        description: current balance of the account

  Transaction:
    properties:
      id:
        type: string
        description: unique identifier for the transaction
      accountId:
        type: string
        description: identifier for the account the transaction is attached to
      date:
        type: string
        format: date
        description: date of the transaction
      amount:
        type: number
        format: double
        description: amount of the transaction (can be positive or negative)
      type:
        type: string
        description: type of transaction
      note:
        type: string
        description: note about the transaction (optional)
